### ISSUE TITLE
Quarkus Continuous Integration Definition (Tekton)

### ISSUE THREAD

**Issue by davgordo** [halkyonio/software-templates#1]
As a Developer
I can onboard a new quarkus application component and a CI pipeline is provisioned automatically
So that I can build the application component

**Scenario:**
Given: An authenticated developer onboarding a new app component in Backstage
When: The Developer selects a Quarkus template
Then: A Tekton pipeline is automatically configured and provisioned that can build the component

Acceptable pipeline:
- code is built
- image is built
- image pushed to image repository

Assumption:
- Tekton is provisioned and available
- Quay org is available and a service account has permission to push to it
- Environments (namespaces) are already provisioned via Backstage "new application" workflow

**Comment by jayfray12** [comment]
Investigated the use of [Pipeline as Code](https://docs.openshift.com/container-platform/4.11/cicd/pipelines/using-pipelines-as-code.html#installing-pipelines-as-code-cli_using-pipelines-as-code) however this is still tech preview and immature at this stage.

Sticking with just the Tekton Pipelines and a helm chart.

PR found here:
https://github.com/halkyonio/software-templates/pull/10
