### ISSUE TITLE
Quarkus App Deployment Manifest (k8s/ArgoCD)

### ISSUE THREAD

**Issue by davgordo** [halkyonio/software-templates#2]
As a Developer
I can onboard a new backstage application with predefined environment manifest
So that the application's environments are automatically provisioned at the end of the workflow

**Scenario:**
Given: An authenticated developer 
When: the developer creates a new application in the Backstage UI
Then: the namespaces/environment are provisioned automatically

**Comment by oladapooloyede** [comment]
Added namespace resource to helm templates in this git commit:- https://github.com/halkyonio/software-templates/pull/9/commits/90a9fd143aeb6cf67977c9329a142b40a0f51e4a
